#!/bin/bash
diff <(bcftools annotate -a inputs/annotate.tab.gz -h test/annotate.hdr -c CHROM,POS,REF,ALT,ID,QUAL,INFO/T_INT,INFO/T_FLOAT,INDEL test/annotate.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/annotate.out)
diff <(bcftools annotate -Ob -a inputs/annotate.tab.gz -h test/annotate.hdr -c CHROM,POS,REF,ALT,ID,QUAL,INFO/T_INT,INFO/T_FLOAT,INDEL test/annotate.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/annotate.out)
diff <(bcftools annotate -a inputs/annotate2.tab.gz -h test/annotate.hdr -c CHROM,FROM,TO,T_STR test/annotate.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/annotate2.out)
diff <(bcftools annotate -Ob -a inputs/annotate2.tab.gz -h test/annotate.hdr -c CHROM,FROM,TO,T_STR test/annotate.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/annotate2.out)
diff <(bcftools annotate -a inputs/annots.vcf.gz  -c STR,ID,QUAL,FILTER inputs/annotate.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/annotate3.out)
diff <(bcftools annotate -Ob -a inputs/annots.vcf.gz  -c STR,ID,QUAL,FILTER inputs/annotate.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/annotate3.out)
diff <(bcftools annotate -a inputs/annots2.vcf.gz  -c ID,QUAL,FILTER,INFO,FMT inputs/annotate2.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/annotate4.out)
diff <(bcftools annotate -Ob -a inputs/annots2.vcf.gz  -c ID,QUAL,FILTER,INFO,FMT inputs/annotate2.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/annotate4.out)
diff <(bcftools annotate -a inputs/annots2.vcf.gz  -c ID,QUAL,+FILTER,+INFO,FMT/GT -s A inputs/annotate2.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/annotate5.out)
diff <(bcftools annotate -Ob -a inputs/annots2.vcf.gz  -c ID,QUAL,+FILTER,+INFO,FMT/GT -s A inputs/annotate2.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/annotate5.out)
diff <(bcftools annotate   -x ID,QUAL,^FILTER/fltA,FILTER/fltB,^INFO/AA,INFO/BB,^FMT/GT,FMT/PL test/annotate3.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/annotate6.out)
diff <(bcftools annotate -Ob   -x ID,QUAL,^FILTER/fltA,FILTER/fltB,^INFO/AA,INFO/BB,^FMT/GT,FMT/PL test/annotate3.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/annotate6.out)
diff <(bcftools annotate   -x FORMAT test/annotate3.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/annotate7.out)
diff <(bcftools annotate -Ob   -x FORMAT test/annotate3.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/annotate7.out)
diff <(bcftools annotate -a inputs/annots4.vcf.gz  -c +INFO inputs/annotate4.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/annotate8.out)
diff <(bcftools annotate -Ob -a inputs/annots4.vcf.gz  -c +INFO inputs/annotate4.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/annotate8.out)
diff <(bcftools annotate -a inputs/annots4.tab.gz -h test/annotate4.hdr -c CHROM,POS,REF,ALT,+FA,+FR,+IA,+IR,+SA,+SR test/annotate4.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/annotate8.out)
diff <(bcftools annotate -Ob -a inputs/annots4.tab.gz -h test/annotate4.hdr -c CHROM,POS,REF,ALT,+FA,+FR,+IA,+IR,+SA,+SR test/annotate4.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/annotate8.out)
diff <(bcftools annotate --rename-chrs inputs/rename.map -Ov inputs/annotate.bcf | bcftools query -f'%CHROM\t%POS\n') <(cat test/rename.out.tmp)
diff <(bcftools annotate --rename-chrs inputs/rename.map -Ob inputs/annotate.bcf | bcftools query -f'%CHROM\t%POS\n') <(cat test/rename.out.tmp)
diff <(bcftools annotate --rename-chrs inputs/rename.map -Ov test/annotate.vcf | bcftools query -f'%CHROM\t%POS\n') <(cat test/rename.out.tmp)
diff <(bcftools annotate --rename-chrs inputs/rename.map -Ob test/annotate.vcf | bcftools query -f'%CHROM\t%POS\n') <(cat test/rename.out.tmp)
