#!/bin/bash
diff <(bcftools concat   inputs/concat.1.a.vcf.gz inputs/concat.1.b.vcf.gz | grep -v ^##bcftools_) <(cat test/concat.1.vcf.out)
diff <(bcftools concat -Ob   inputs/concat.1.a.vcf.gz inputs/concat.1.b.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/concat.1.vcf.out)
diff <(bcftools concat   inputs/concat.1.a.bcf inputs/concat.1.b.bcf | grep -v ^##bcftools_) <(cat test/concat.1.bcf.out)
diff <(bcftools concat -Ob   inputs/concat.1.a.bcf inputs/concat.1.b.bcf | bcftools view | grep -v ^##bcftools_) <(cat test/concat.1.bcf.out)
diff <(bcftools concat -a  inputs/concat.2.a.vcf.gz inputs/concat.2.b.vcf.gz | grep -v ^##bcftools_) <(cat test/concat.2.vcf.out)
diff <(bcftools concat -Ob -a  inputs/concat.2.a.vcf.gz inputs/concat.2.b.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/concat.2.vcf.out)
diff <(bcftools concat -a  inputs/concat.2.a.bcf inputs/concat.2.b.bcf | grep -v ^##bcftools_) <(cat test/concat.2.bcf.out)
diff <(bcftools concat -Ob -a  inputs/concat.2.a.bcf inputs/concat.2.b.bcf | bcftools view | grep -v ^##bcftools_) <(cat test/concat.2.bcf.out)
diff <(bcftools concat -aD  inputs/concat.2.a.vcf.gz inputs/concat.2.b.vcf.gz | grep -v ^##bcftools_) <(cat test/concat.4.vcf.out)
diff <(bcftools concat -Ob -aD  inputs/concat.2.a.vcf.gz inputs/concat.2.b.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/concat.4.vcf.out)
diff <(bcftools concat -aD  inputs/concat.2.a.bcf inputs/concat.2.b.bcf | grep -v ^##bcftools_) <(cat test/concat.4.bcf.out)
diff <(bcftools concat -Ob -aD  inputs/concat.2.a.bcf inputs/concat.2.b.bcf | bcftools view | grep -v ^##bcftools_) <(cat test/concat.4.bcf.out)
diff <(bcftools concat -l  inputs/concat.3.a.vcf.gz inputs/concat.3.b.vcf.gz inputs/concat.3.0.vcf.gz inputs/concat.3.c.vcf.gz inputs/concat.3.d.vcf.gz inputs/concat.3.e.vcf.gz inputs/concat.3.f.vcf.gz | grep -v ^##bcftools_) <(cat test/concat.3.vcf.out)
diff <(bcftools concat -Ob -l  inputs/concat.3.a.vcf.gz inputs/concat.3.b.vcf.gz inputs/concat.3.0.vcf.gz inputs/concat.3.c.vcf.gz inputs/concat.3.d.vcf.gz inputs/concat.3.e.vcf.gz inputs/concat.3.f.vcf.gz | bcftools view | grep -v ^##bcftools_) <(cat test/concat.3.vcf.out)
diff <(bcftools concat -l  inputs/concat.3.a.bcf inputs/concat.3.b.bcf inputs/concat.3.0.bcf inputs/concat.3.c.bcf inputs/concat.3.d.bcf inputs/concat.3.e.bcf inputs/concat.3.f.bcf | grep -v ^##bcftools_) <(cat test/concat.3.bcf.out)
diff <(bcftools concat -Ob -l  inputs/concat.3.a.bcf inputs/concat.3.b.bcf inputs/concat.3.0.bcf inputs/concat.3.c.bcf inputs/concat.3.d.bcf inputs/concat.3.e.bcf inputs/concat.3.f.bcf | bcftools view | grep -v ^##bcftools_) <(cat test/concat.3.bcf.out)
