#!/bin/bash
diff <(bcftools convert -g -,. inputs/convert.vcf.gz) <(cat test/convert.gs.gt.gen)
diff <(bcftools convert -g .,- inputs/convert.vcf.gz) <(cat test/convert.gs.gt.samples)
diff <(bcftools convert -g -,. --tag PL inputs/convert.vcf.gz) <(cat test/convert.gs.pl.gen)
diff <(bcftools convert -g .,- --tag PL inputs/convert.vcf.gz) <(cat test/convert.gs.pl.samples)
diff <(bcftools convert -g -,. --vcf-ids inputs/check.vcf.gz) <(cat test/check.gs.vcfids.gen)
diff <(bcftools convert -g .,- --vcf-ids inputs/check.vcf.gz) <(cat test/check.gs.vcfids.samples)
diff <(bcftools convert -g -,. --chrom inputs/check.vcf.gz) <(cat test/check.gs.chrom.gen)
diff <(bcftools convert -g .,- --chrom inputs/check.vcf.gz) <(cat test/check.gs.chrom.samples)
diff <(bcftools convert -g -,. --chrom --vcf-ids inputs/check.vcf.gz) <(cat test/check.gs.vcfids_chrom.gen)
diff <(bcftools convert -g .,- --chrom --vcf-ids inputs/check.vcf.gz) <(cat test/check.gs.vcfids_chrom.samples)
diff <(bcftools convert -h -,.,. inputs/convert.vcf.gz) <(cat test/convert.hls.haps)
diff <(bcftools convert -h .,-,. inputs/convert.vcf.gz) <(cat test/convert.hls.legend)
diff <(bcftools convert -h .,.,- inputs/convert.vcf.gz) <(cat test/convert.hls.samples)
diff <(bcftools convert --hapsample -,. inputs/convert.vcf.gz) <(cat test/convert.hs.hap)
diff <(bcftools convert --hapsample .,- inputs/convert.vcf.gz) <(cat test/convert.hs.sample)
diff <(bcftools convert --gvcf2vcf inputs/convert.gvcf.vcf.gz | grep -v ^##bcftools) <(cat test/convert.gvcf.out)
diff <(bcftools convert  -c ID,CHROM,POS,AA -s SAMPLE1 -f test/23andme.fa --tsv2vcf test/convert.23andme | grep -v ^##bcftools_) <(cat test/convert.23andme.vcf)
diff <(bcftools convert -Ou  -c ID,CHROM,POS,AA -s SAMPLE1 -f test/23andme.fa --tsv2vcf test/convert.23andme | bcftools view | grep -v ^##bcftools_) <(cat test/convert.23andme.vcf)
