#!/bin/bash
diff <(bcftools filter -S. -e'TXT0="text"' test/view.filter.vcf | grep -v ^##bcftools_) <(cat test/view.filter.6.out)
diff <(bcftools filter -Ob -S. -e'TXT0="text"' test/view.filter.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/view.filter.6.out)
diff <(bcftools filter -S. -e'FMT/FRS[1]="BB"' test/view.filter.vcf | grep -v ^##bcftools_) <(cat test/view.filter.7.out)
diff <(bcftools filter -Ob -S. -e'FMT/FRS[1]="BB"' test/view.filter.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/view.filter.7.out)
diff <(bcftools filter -S. -e'FMT/FGS[0]="AAAAAA"' test/view.filter.vcf | grep -v ^##bcftools_) <(cat test/view.filter.8.out)
diff <(bcftools filter -Ob -S. -e'FMT/FGS[0]="AAAAAA"' test/view.filter.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/view.filter.8.out)
diff <(bcftools filter -S. -e'FMT/FGS[1]="BBB"' test/view.filter.vcf | grep -v ^##bcftools_) <(cat test/view.filter.9.out)
diff <(bcftools filter -Ob -S. -e'FMT/FGS[1]="BBB"' test/view.filter.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/view.filter.9.out)
diff <(bcftools filter -S. -e'FMT/FGS[4]="EE"' test/view.filter.vcf | grep -v ^##bcftools_) <(cat test/view.filter.10.out)
diff <(bcftools filter -Ob -S. -e'FMT/FGS[4]="EE"' test/view.filter.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/view.filter.10.out)
diff <(bcftools filter -S. -e'FMT/STR="XX"' test/view.filter.vcf | grep -v ^##bcftools_) <(cat test/view.filter.11.out)
diff <(bcftools filter -Ob -S. -e'FMT/STR="XX"' test/view.filter.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/view.filter.11.out)
diff <(bcftools filter -mx -g2 -G2 test/filter.1.vcf | grep -v ^##bcftools_) <(cat test/filter.1.out)
diff <(bcftools filter -Ob -mx -g2 -G2 test/filter.1.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/filter.1.out)
diff <(bcftools filter -e'QUAL==59.2) <(cat (INDEL=0 & (FMT/GQ=25 | FMT/DP=10))' -sModified -S. test/filter.2.vcf | grep -v ^##bcftools_) <(cat test/filter.2.out)
diff <(bcftools filter -Ob -e'QUAL==59.2) <(cat (INDEL=0 & (FMT/GQ=25 | FMT/DP=10))' -sModified -S. test/filter.2.vcf | bcftools view | grep -v ^##bcftools_) <(cat test/filter.2.out)
diff <(bcftools filter -e'DP=19' test/filter.3.vcf | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.3.out)
diff <(bcftools filter -Ob -e'DP=19' test/filter.3.vcf | bcftools view | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.3.out)
diff <(bcftools filter -e'DP=19' -s XX test/filter.3.vcf | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.4.out)
diff <(bcftools filter -Ob -e'DP=19' -s XX test/filter.3.vcf | bcftools view | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.4.out)
diff <(bcftools filter -e'DP=19' -s XX -m+ test/filter.3.vcf | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.5.out)
diff <(bcftools filter -Ob -e'DP=19' -s XX -m+ test/filter.3.vcf | bcftools view | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.5.out)
diff <(bcftools filter -e'DP=19' -s XX -mx test/filter.3.vcf | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.6.out)
diff <(bcftools filter -Ob -e'DP=19' -s XX -mx test/filter.3.vcf | bcftools view | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.6.out)
diff <(bcftools filter -e'DP=19' -s XX -m+x test/filter.3.vcf | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.7.out)
diff <(bcftools filter -Ob -e'DP=19' -s XX -m+x test/filter.3.vcf | bcftools view | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.7.out)
diff <(bcftools filter -e'FMT/GT="0/2"' test/filter.3.vcf | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.3.out)
diff <(bcftools filter -Ob -e'FMT/GT="0/2"' test/filter.3.vcf | bcftools view | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.3.out)
diff <(bcftools filter -e'FMT/GT="0/2"' -s XX test/filter.3.vcf | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.4.out)
diff <(bcftools filter -Ob -e'FMT/GT="0/2"' -s XX test/filter.3.vcf | bcftools view | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.4.out)
diff <(bcftools filter -e'FMT/GT="0/2"' -s XX -m+ test/filter.3.vcf | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.5.out)
diff <(bcftools filter -Ob -e'FMT/GT="0/2"' -s XX -m+ test/filter.3.vcf | bcftools view | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.5.out)
diff <(bcftools filter -e'FMT/GT="0/2"' -s XX -mx test/filter.3.vcf | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.6.out)
diff <(bcftools filter -Ob -e'FMT/GT="0/2"' -s XX -mx test/filter.3.vcf | bcftools view | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.6.out)
diff <(bcftools filter -e'FMT/GT="0/2"' -s XX -m+x test/filter.3.vcf | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.7.out)
diff <(bcftools filter -Ob -e'FMT/GT="0/2"' -s XX -m+x test/filter.3.vcf | bcftools view | bcftools query -f '%POS\t%FILTER\t%DP[\t%GT]\n') <(cat test/filter.7.out)
diff <(bcftools filter -i'FMT/GT="0/0" && AC[*]=2' test/filter.2.vcf | bcftools query -f '%POS\t%AC[\t%GT]\n') <(cat test/filter.8.out)
diff <(bcftools filter -Ob -i'FMT/GT="0/0" && AC[*]=2' test/filter.2.vcf | bcftools view | bcftools query -f '%POS\t%AC[\t%GT]\n') <(cat test/filter.8.out)
diff <(bcftools filter -i'AC[*]=2 && FMT/GT="0/0"' test/filter.2.vcf | bcftools query -f '%POS\t%AC[\t%GT]\n') <(cat test/filter.8.out)
diff <(bcftools filter -Ob -i'AC[*]=2 && FMT/GT="0/0"' test/filter.2.vcf | bcftools view | bcftools query -f '%POS\t%AC[\t%GT]\n') <(cat test/filter.8.out)
