#!/bin/bash
diff <(bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t%DP4\t%AN[\t%GT\t%TGT]\n' inputs/query.vcf.gz) <(cat test/query.out)
diff <(bcftools query -f'%XRI\n' -i'XRI[*]>1111' inputs/view.filter.vcf.gz) <(cat test/query.2.out)
diff <(bcftools query -f'%XRF\n' -i'XRF[*]=2e6' inputs/view.filter.vcf.gz) <(cat test/query.3.out)
diff <(bcftools query -f'%XGS\n' -i'XGS[5]="PQR"' inputs/view.filter.vcf.gz) <(cat test/query.4.out)
diff <(bcftools query -f'%XGS\n' -i'XGS[*]="GHI"' inputs/view.filter.vcf.gz) <(cat test/query.4.out)
diff <(bcftools query -f'%XGS\n' -i'XGS[2]~"H"' inputs/view.filter.vcf.gz) <(cat test/query.4.out)
diff <(bcftools query -f'%XGS\n' -i'XGS[3]!~"H"' inputs/view.filter.vcf.gz) <(cat test/query.4.out)
diff <(bcftools query -f'%XGS\n' -i'XGS[*]~"H"' inputs/view.filter.vcf.gz) <(cat test/query.4.out)
diff <(bcftools query -f'%XGS\n' -i'XGS[*]~"HI,JK"' inputs/view.filter.vcf.gz) <(cat test/query.4.out)
diff <(bcftools query -f'%POS %REF %ALT\n' -i'REF~"C" && ALT~"CT"' inputs/query.vcf.gz) <(cat test/query.5.out)
diff <(bcftools query -f'%POS %REF %ALT\n' -i'N_ALT=2' inputs/query.vcf.gz) <(cat test/query.6.out)
diff <(bcftools query -f'%POS %AN\n' -i'AN!=2*N_SAMPLES' inputs/query.vcf.gz) <(cat test/query.7.out)
diff <(bcftools query -f'%POS[ %GL]\n' -i'min(abs(GL[0]))=10' inputs/query.vcf.gz) <(cat test/query.8.out)
diff <(bcftools query -f'%POS %CIGAR\n' -i'strlen(CIGAR[*])=4' inputs/view.filter.vcf.gz) <(cat test/query.9.out)
diff <(bcftools query -f'%POS[ %GT]\n' -i'AC[0]=3' inputs/query.vcf.gz) <(cat test/query.10.out)
diff <(bcftools query -f'%POS[ %GT]\n' -i'AF[0]=3/4' inputs/query.vcf.gz) <(cat test/query.10.out)
diff <(bcftools query -f'%POS[ %GT]\n' -i'MAC[0]=1' inputs/query.vcf.gz) <(cat test/query.11.out)
diff <(bcftools query -f'%POS[ %GT]\n' -i'MAF[0]=1/4' inputs/query.vcf.gz) <(cat test/query.11.out)
diff <(bcftools query -f'I8=%I8 I16=%I16 I32=%I32 IF=%IF IA8=%IA8 IA16=%IA16 IA32=%IA32 IAF=%IAF IA8=%IA8{1} IA16=%IA16{1} IA32=%IA32{1} IAF=%IAF{1} [ %F8:%F16:%F32:%FF]\n' inputs/view.vectors.vcf.gz) <(cat test/query.12.out)
diff <(bcftools query -f'%POS[ %GT]\n' -i'GT ="1"' inputs/query.filter.vcf.gz) <(cat test/query.13.out)
diff <(bcftools query -f'%POS[ %GT]\n' -i'GT!="1"' inputs/query.filter.vcf.gz) <(cat test/query.14.out)
diff <(bcftools query -f'%POS[ %GT]\n' -e'GT ="1"' inputs/query.filter.vcf.gz) <(cat test/query.15.out)
diff <(bcftools query -f'%POS[ %GT]\n' -e'GT!="1"' inputs/query.filter.vcf.gz) <(cat test/query.16.out)
diff <(bcftools query -f'%XX_A %XX.A %XX.A0 %xx.a0\n' inputs/query.2.vcf.gz) <(cat test/query.17.out)
diff <(bcftools query -f'%CHROM %POS %REF,%ALT\n' -T test/regions.tab inputs/regions.vcf.gz) <(cat test/regions.out)
diff <(bcftools query -f'%CHROM %POS %REF,%ALT\n' -R test/regions.tab inputs/regions.vcf.gz) <(cat test/regions.out)
diff <(bcftools query -f'%CHROM %POS %REF,%ALT\n' -T inputs/regions.tab.gz inputs/regions.vcf.gz) <(cat test/regions.out)
diff <(bcftools query -f'%CHROM %POS %REF,%ALT\n' -R inputs/regions.tab.gz inputs/regions.vcf.gz) <(cat test/regions.out)
diff <(bcftools query -f'%CHROM %POS %REF,%ALT\n' -T inputs/regions.bed inputs/regions.vcf.gz) <(cat test/regions.out)
diff <(bcftools query -f'%CHROM %POS %REF,%ALT\n' -R inputs/regions.bed inputs/regions.vcf.gz) <(cat test/regions.out)
diff <(bcftools query -f'%CHROM %POS %REF,%ALT\n' -T inputs/regions.bed.gz inputs/regions.vcf.gz) <(cat test/regions.out)
diff <(bcftools query -f'%CHROM %POS %REF,%ALT\n' -R inputs/regions.bed.gz inputs/regions.vcf.gz) <(cat test/regions.out)
