#!/bin/bash
diff <(bcftools view -H inputs/merge.a.bcf 2:3199812-3199812) <(cat test/tabix.2.3199812.out)
diff <(bcftools view -H inputs/merge.a.bcf 1:3000151-3000151) <(cat test/tabix.1.3000151.out)
diff <(bcftools view -H inputs/large_chrom_tbi_limit.bcf chr11:1-536870912) <(cat test/large_chrom_tbi_limit.20.1.536870912.out)
diff <(bcftools view -H inputs/large_chrom_csi_limit.vcf.gz chr20:1-2147483647) <(cat test/large_chrom_csi_limit.20.1.2147483647.out)
diff <(bcftools view -H inputs/large_chrom_csi_limit.bcf chr20:1-2147483647) <(cat test/large_chrom_csi_limit.20.1.2147483647.out)
diff <(bcftools view -H inputs/large_chrom_csi_limit.vcf.gz chr20) <(cat test/large_chrom.20.1.2147483647.out)
diff <(bcftools view -H inputs/large_chrom_csi_limit.bcf chr20) <(cat test/large_chrom.20.1.2147483647.out)
diff <(bcftools view -Ob inputs/check.vcf.gz | bcftools stats -s - | grep -v '^# The command' | grep -v '^# This' | grep -v '^IDdiff <(') <(cat test/check.chk)
diff <(bcftools view -Ob inputs/query.vcf.gz | bcftools query -f '%CHROM\t%POS\t%REF\t%ALT\t%DP4\t%AN[\t%GT\t%TGT]\n') <(cat test/query.out)
diff <(bcftools view -Ob inputs/view.filter.vcf.gz | bcftools query -f'%XRI\n' -i'XRI[*]>1111') <(cat test/query.2.out)
diff <(bcftools view -Ob inputs/view.filter.vcf.gz | bcftools query -f'%XRF\n' -i'XRF[*]=2e6') <(cat test/query.3.out)
diff <(bcftools view -Ob inputs/view.filter.vcf.gz | bcftools query -f'%XGS\n' -i'XGS[5]="PQR"') <(cat test/query.4.out)
diff <(bcftools view -Ob inputs/view.filter.vcf.gz | bcftools query -f'%XGS\n' -i'XGS[*]="GHI"') <(cat test/query.4.out)
diff <(bcftools view -Ob inputs/view.filter.vcf.gz | bcftools query -f'%XGS\n' -i'XGS[2]~"H"') <(cat test/query.4.out)
diff <(bcftools view -Ob inputs/view.filter.vcf.gz | bcftools query -f'%XGS\n' -i'XGS[3]!~"H"') <(cat test/query.4.out)
diff <(bcftools view -Ob inputs/view.filter.vcf.gz | bcftools query -f'%XGS\n' -i'XGS[*]~"H"') <(cat test/query.4.out)
diff <(bcftools view -Ob inputs/view.filter.vcf.gz | bcftools query -f'%XGS\n' -i'XGS[*]~"HI,JK"') <(cat test/query.4.out)
diff <(bcftools view -Ob inputs/query.vcf.gz | bcftools query -f'%POS %REF %ALT\n' -i'REF~"C" && ALT~"CT"') <(cat test/query.5.out)
diff <(bcftools view -Ob inputs/query.vcf.gz | bcftools query -f'%POS %REF %ALT\n' -i'N_ALT=2') <(cat test/query.6.out)
diff <(bcftools view -Ob inputs/query.vcf.gz | bcftools query -f'%POS %AN\n' -i'AN!=2*N_SAMPLES') <(cat test/query.7.out)
diff <(bcftools view -Ob inputs/query.vcf.gz | bcftools query -f'%POS[ %GL]\n' -i'min(abs(GL[0]))=10') <(cat test/query.8.out)
diff <(bcftools view -Ob inputs/view.filter.vcf.gz | bcftools query -f'%POS %CIGAR\n' -i'strlen(CIGAR[*])=4') <(cat test/query.9.out)
diff <(bcftools view -Ob inputs/query.vcf.gz | bcftools query -f'%POS[ %GT]\n' -i'AC[0]=3') <(cat test/query.10.out)
diff <(bcftools view -Ob inputs/query.vcf.gz | bcftools query -f'%POS[ %GT]\n' -i'AF[0]=3/4') <(cat test/query.10.out)
diff <(bcftools view -Ob inputs/query.vcf.gz | bcftools query -f'%POS[ %GT]\n' -i'MAC[0]=1') <(cat test/query.11.out)
diff <(bcftools view -Ob inputs/query.vcf.gz | bcftools query -f'%POS[ %GT]\n' -i'MAF[0]=1/4') <(cat test/query.11.out)
diff <(bcftools view -Ob inputs/view.vectors.vcf.gz | bcftools query -f'I8=%I8 I16=%I16 I32=%I32 IF=%IF IA8=%IA8 IA16=%IA16 IA32=%IA32 IAF=%IAF IA8=%IA8{1} IA16=%IA16{1} IA32=%IA32{1} IAF=%IAF{1} [ %F8:%F16:%F32:%FF]\n') <(cat test/query.12.out)
diff <(bcftools view -Ob inputs/query.filter.vcf.gz | bcftools query -f'%POS[ %GT]\n' -i'GT ="1"') <(cat test/query.13.out)
diff <(bcftools view -Ob inputs/query.filter.vcf.gz | bcftools query -f'%POS[ %GT]\n' -i'GT!="1"') <(cat test/query.14.out)
diff <(bcftools view -Ob inputs/query.filter.vcf.gz | bcftools query -f'%POS[ %GT]\n' -e'GT ="1"') <(cat test/query.15.out)
diff <(bcftools view -Ob inputs/query.filter.vcf.gz | bcftools query -f'%POS[ %GT]\n' -e'GT!="1"') <(cat test/query.16.out)
diff <(bcftools view -Ob inputs/query.2.vcf.gz | bcftools query -f'%XX_A %XX.A %XX.A0 %xx.a0\n') <(cat test/query.17.out)
diff <(bcftools view -aUc1 -C1 -s NA00002 -v snps inputs/view.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.1.out)
diff <(bcftools view -Ob -aUc1 -C1 -s NA00002 -v snps inputs/view.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.1.out)
diff <(bcftools view -f PASS -Xks NA00003 inputs/view.vcf.gz -r20,Y | grep -v ^##bcftools_) <(cat test/view.2.out)
diff <(bcftools view -Ob -f PASS -Xks NA00003 inputs/view.vcf.gz -r20,Y | bcftools view | grep -v ^##bcftools_) <(cat test/view.2.out)
diff <(bcftools view -xs NA00003 inputs/view.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.3.out)
diff <(bcftools view -Ob -xs NA00003 inputs/view.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.3.out)
diff <(bcftools view -i 'QUAL==999 && (FS<20) <(cat FS>=41.02) && ICF>-0.1 && HWE*2>1.2' inputs/view.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.4.out)
diff <(bcftools view -Ob -i 'QUAL==999 && (FS<20) <(cat FS>=41.02) && ICF>-0.1 && HWE*2>1.2' inputs/view.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.4.out)
diff <(bcftools view -p inputs/view.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.5.out)
diff <(bcftools view -Ob -p inputs/view.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.5.out)
diff <(bcftools view -P inputs/view.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.6.out)
diff <(bcftools view -Ob -P inputs/view.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.6.out)
diff <(bcftools view -hm2 -M2 -q0.3 -Q0.7 inputs/view.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.7.out)
diff <(bcftools view -Ob -hm2 -M2 -q0.3 -Q0.7 inputs/view.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.7.out)
diff <(bcftools view -Hu inputs/view.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.8.out)
diff <(bcftools view -GVsnps inputs/view.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.9.out)
diff <(bcftools view -Ob -GVsnps inputs/view.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.9.out)
diff <(bcftools view -ne 'INDEL=1) <(cat PV4[0]<0.006' inputs/view.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.10.out)
diff <(bcftools view -Ob -ne 'INDEL=1) <(cat PV4[0]<0.006' inputs/view.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.10.out)
diff <(bcftools view -s ^NA00003 inputs/view.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.exclude.out)
diff <(bcftools view -Ob -s ^NA00003 inputs/view.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.exclude.out)
diff <(bcftools view  inputs/view.omitgenotypes.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.omitgenotypes.out)
diff <(bcftools view -Ob  inputs/view.omitgenotypes.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.omitgenotypes.out)
diff <(bcftools view -asA inputs/view.vectors.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.vectors.A.out)
diff <(bcftools view -Ob -asA inputs/view.vectors.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.vectors.A.out)
diff <(bcftools view -asB inputs/view.vectors.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.vectors.B.out)
diff <(bcftools view -Ob -asB inputs/view.vectors.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.vectors.B.out)
diff <(bcftools view -H -i'FMT/FGS[0]="AAAAAA"' inputs/view.filter.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.filter.1.out)
diff <(bcftools view -H -i'FMT/FGS[2]="C"' inputs/view.filter.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.filter.2.out)
diff <(bcftools view -H -i'FMT/FGS[4]="EE"' inputs/view.filter.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.filter.3.out)
diff <(bcftools view -H -i'FMT/FRS[1]="BB"' inputs/view.filter.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.filter.4.out)
diff <(bcftools view -H -i'TXT0="text"' inputs/view.filter.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.filter.5.out)
diff <(bcftools view -T test/view.chrs.tab inputs/view.chrs.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.chrs.out)
diff <(bcftools view -Ob -T test/view.chrs.tab inputs/view.chrs.vcf.gz  | bcftools view | grep -v ^##bcftools_) <(cat test/view.chrs.out)
diff <(bcftools view -H -C5:nonmajor inputs/view.minmaxac.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.minmaxac.1.out)
diff <(bcftools view -H -c6:nonmajor inputs/view.minmaxac.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.minmaxac.2.out)
diff <(bcftools view -H -q0.3:major inputs/view.minmaxac.vcf.gz  | grep -v ^##bcftools_) <(cat test/view.minmaxac.1.out)
diff <(bcftools view -Ob inputs/regions.vcf.gz | bcftools query -f'%CHROM %POS %REF,%ALT\n' -T test/regions.tab) <(cat test/regions.out)
diff <(bcftools view -Ob inputs/regions.vcf.gz | bcftools query -f'%CHROM %POS %REF,%ALT\n' -T inputs/regions.tab.gz) <(cat test/regions.out)
diff <(bcftools view -Ob inputs/regions.vcf.gz | bcftools query -f'%CHROM %POS %REF,%ALT\n' -T inputs/regions.bed) <(cat test/regions.out)
diff <(bcftools view -Ob inputs/regions.vcf.gz | bcftools query -f'%CHROM %POS %REF,%ALT\n' -T inputs/regions.bed.gz) <(cat test/regions.out)
diff <(bcftools view -Ob inputs/convert.vcf.gz | bcftools convert -g -,.) <(cat test/convert.gs.gt.gen)
diff <(bcftools view -Ob inputs/convert.vcf.gz | bcftools convert -g .,-) <(cat test/convert.gs.gt.samples)
diff <(bcftools view -Ob inputs/convert.vcf.gz | bcftools convert -g -,. --tag PL) <(cat test/convert.gs.pl.gen)
diff <(bcftools view -Ob inputs/convert.vcf.gz | bcftools convert -g .,- --tag PL) <(cat test/convert.gs.pl.samples)
diff <(bcftools view -Ob inputs/check.vcf.gz | bcftools convert -g -,. --vcf-ids) <(cat test/check.gs.vcfids.gen)
diff <(bcftools view -Ob inputs/check.vcf.gz | bcftools convert -g .,- --vcf-ids) <(cat test/check.gs.vcfids.samples)
diff <(bcftools view -Ob inputs/check.vcf.gz | bcftools convert -g -,. --chrom) <(cat test/check.gs.chrom.gen)
diff <(bcftools view -Ob inputs/check.vcf.gz | bcftools convert -g .,- --chrom) <(cat test/check.gs.chrom.samples)
diff <(bcftools view -Ob inputs/check.vcf.gz | bcftools convert -g -,. --chrom --vcf-ids) <(cat test/check.gs.vcfids_chrom.gen)
diff <(bcftools view -Ob inputs/check.vcf.gz | bcftools convert -g .,- --chrom --vcf-ids) <(cat test/check.gs.vcfids_chrom.samples)
diff <(bcftools view -Ob inputs/convert.vcf.gz | bcftools convert -h -,.,.) <(cat test/convert.hls.haps)
diff <(bcftools view -Ob inputs/convert.vcf.gz | bcftools convert -h .,-,.) <(cat test/convert.hls.legend)
diff <(bcftools view -Ob inputs/convert.vcf.gz | bcftools convert -h .,.,-) <(cat test/convert.hls.samples)
diff <(bcftools view -Ob inputs/convert.vcf.gz | bcftools convert --hapsample -,.) <(cat test/convert.hs.hap)
diff <(bcftools view -Ob inputs/convert.vcf.gz | bcftools convert --hapsample .,-) <(cat test/convert.hs.sample)
diff <(bcftools view -Ob inputs/convert.gvcf.vcf.gz | bcftools convert --gvcf2vcf | grep -v ^##bcftools) <(cat test/convert.gvcf.out)
